- platform: command_line
  name: New Commits
  scan_interval: 600
  command: "git fetch origin && git log dev..origin/dev --pretty=oneline | wc -l"
- platform: command_line
  name: Home Assistant Errors
  scan_interval: 3600
  command: !secret ha_error_command
- platform: command_line
  name: Home Assistant Warnings
  scan_interval: 3600
  command: !secret ha_warning_command
