#- platform: command_line
#  scan_interval: 3600
#  name: Heating Oil Delivery
#  command: !env_var HEATING_OIL_WGET
#  unit_of_measurement: 'gal'
#  value_template: '{{value_json.aaData[0].units|round}}'
- platform: command_line
  name: New Commits
  command: "git fetch origin && git log dev..origin/dev --pretty=oneline | wc -l"
- platform: command_line
  name: Home Assistant Errors
  command: !secret ha_error_command
- platform: command_line
  name: Home Assistant Warnings
  command: !secret ha_warning_command
