- platform: rest
  scan_interval: 3600
  resource: 'http://api.forismatic.com/api/1.0/?method=getQuote&format=text&lang=en'
  method: GET
  name: Quote
  value_template: '{{value.split(" (")[0]}}'
- platform: rest
  scan_interval: 7200
  resource: !secret horoscope_url
  name: His Horoscope
  value_template: !secret his_horoscope_path
- platform: rest
  scan_interval: 7200
  resource: !secret horoscope_url
  name: Her Horoscope
  value_template: !secret her_horoscope_path
