- platform: rest
  scan_interval: 3600
  resource: !secret gas_buddy_resource
  method: POST
  name: Gas Price
  value_template: '{{value_json.trend.Today}}'
  unit_of_measurement: '$'
- platform: rest
  scan_interval: 3600
  resource: 'http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en'
  method: GET
  name: Quote
  value_template: '{{value_json.quoteText}}'
