- platform: template
  sensors:
    front_door_lock_battery:
      value_template: '{{states.zwave.zwave_lock.attributes.battery_level}}'
      unit_of_measurement: '%'
      friendly_name: 'Front Door Lock Battery'
    first_floor_smoke_co_battery:
      value_template: '{{states.zwave.zwave_detector_1.attributes.battery_level}}'
      unit_of_measurement: '%'
      friendly_name: 'First Floor Smoke/CO Alarm Battery'
    second_floor_smoke_co_battery:
      value_template: '{{states.zwave.zwave_detector_2.attributes.battery_level}}'
      unit_of_measurement: '%'
      friendly_name: 'Second Floor Smoke/CO Alarm Battery'
    his_phone_battery:
      value_template: '{{states.device_tracker.his_phone.attributes.battery}}'
      unit_of_measurement: '%'
      friendly_name: 'His Phone Battery'
    her_phone_battery:
      value_template: '{{states.device_tracker.her_phone.attributes.battery}}'
      unit_of_measurement: '%'
      friendly_name: 'Her Phone Battery'
  #    door_one_battery:
  #    value_template: '{{states.sensor.vision_zd2102_eu_doorwindow_sensor_alarm_level_8_1.attributes.battery_level}}'
  #    unit_of_measurement: '%'
  #    friendly_name: 'Side Door Battery'
  #  door_two_battery:
  #    value_template: '{{states.sensor.vision_zd2102_eu_doorwindow_sensor_alarm_level_9_1.attributes.battery_level}}'
  #    unit_of_measurement: '%'
  #    friendly_name: 'Front Door Battery'
