- platform: template
  sensors:
    front_door_lock_battery:
      value_template: '{{(states.zwave.zwave_lock.attributes|default).battery_level|default|int(0)}}'
      unit_of_measurement: '%'
      friendly_name: 'Front Door Lock Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_lock.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    first_floor_smoke_co_battery:
      value_template: '{{(states.zwave.zwave_detector_1.attributes|default).battery_level|default|int(0)}}'
      unit_of_measurement: '%'
      friendly_name: 'First Floor Smoke/CO Alarm Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_detector_1.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    second_floor_smoke_co_battery:
      value_template: '{{(states.zwave.zwave_detector_2.attributes|default).battery_level|default|int(0)}}'
      unit_of_measurement: '%'
      friendly_name: 'Second Floor Smoke/CO Alarm Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_detector_2.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    door_sensor_1_battery:
      value_template: '{{(states.zwave.zwave_door_sensor_1.attributes|default).battery_level|default|int(0)}}'
      unit_of_measurement: '%'
      friendly_name: 'Side Door Sensor Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_door_sensor_1.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    door_sensor_2_battery:
      value_template: '{{(states.zwave.zwave_door_sensor_2.attributes|default).battery_level|default|int(0)}}'
      unit_of_measurement: '%'
      friendly_name: 'Front Door Sensor Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_door_sensor_2.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    door_sensor_3_battery:
      value_template: '{{(states.zwave.zwave_door_sensor_3.attributes|default).battery_level|default|int(0)}}'
      unit_of_measurement: '%'
      friendly_name: 'Den Door Sensor Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_door_sensor_3.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    door_sensor_4_battery:
      value_template: '{{(states.zwave.zwave_door_sensor_4.attributes|default).battery_level|default|int(0)}}'
      unit_of_measurement: '%'
      friendly_name: 'Porch Door Sensor Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_door_sensor_4.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    door_sensor_5_battery:
      value_template: '{{(states.zwave.zwave_door_sensor_5.attributes|default).battery_level|default|int(0)}}'
      unit_of_measurement: '%'
      friendly_name: 'Cat Door Sensor Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_door_sensor_5.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    water_sensor_1_battery:
      value_template: "{{ (states.zwave.zwave_water_sensor_1.attributes|default).battery_level|default|int(0) }}"
      unit_of_measurement: '%'
      friendly_name: 'Garage Water Sensor Battery'
      icon_template: >
        {% set battery_level = (states.zwave.zwave_water_sensor_1.attributes|default).battery_level|default|int(0) %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    his_phone_battery:
      value_template: '{{states.device_tracker.his_phone.attributes.battery}}'
      unit_of_measurement: '%'
      friendly_name: 'His Phone Battery'
      icon_template: >
        {% set battery_level = states.device_tracker.his_phone.attributes.battery | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    her_phone_battery:
      value_template: '{{states.device_tracker.her_phone.attributes.battery}}'
      unit_of_measurement: '%'
      friendly_name: 'Her Phone Battery'
      icon_template: >
        {% set battery_level = states.device_tracker.her_phone.attributes.battery | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
