homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret unit_system
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages:  !include_dir_named packages

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

ecobee:
  api_key: !secret ecobee_api_key

digital_ocean:
  access_token: !secret digitalocean_api_key

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: hass
  keepalive: 60

emulated_hue:
  expose_by_default: false

http:
  api_password: !secret hass_api_password
  base_url: !secret hass_base_url

alexa: !include alexa.yaml
automation: !include_dir_list automation
binary_sensor: !include_dir_merge_list binary_sensors
device_tracker: !include device_trackers.yaml
group: !include_dir_merge_named groups
light: !include light.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
logger: !include logger.yaml
logbook: !include logbook.yaml
weblink: !include weblink.yaml

sun:
frontend:
history:
config:
