homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret unit_system
  time_zone: !secret timezone
  customize: !include_dir_merge_named customizations
  packages:  !include_dir_named packages

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

ecobee:
  api_key: !secret ecobee_api_key

digital_ocean:
  access_token: !secret digitalocean_api_key

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: hass
  keepalive: 60

emulated_hue:
  expose_by_default: false

http:
  api_password: !secret hass_api_password
  base_url: !secret hass_base_url

recorder:
  purge_days: 3
  db_url: !secret recorder_db_url

device_tracker: !include device_trackers.yaml
alexa: !include alexa.yaml
light: !include light.yaml
switch: !include_dir_merge_list switches
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
group: !include groups.yaml
scene: !include scenes.yaml
automation: !include_dir_list automation
notify: !include notify.yaml
weblink: !include weblink.yaml
logger: !include logger.yaml
logbook: !include logbook.yaml

sun:
frontend:
history:
