- platform: limitlessled
  bridges:
  - host: 192.168.2.59
    version: 5
    port: 8899
    groups:
    - number: 1
      type: rgbw
      name: Bedroom Lamp
      #fade: true
    - number: 2
      type: white
      name: Living Room Fan Light
      #fade: true
    - number: 3
      type: rgbw
      name: Stair Lighting
      #fade: true
    - number: 4
      type: rgbw
      name: Living Room Lamps
      #fade: true
