- platform: limitlessled
  bridges:
  - host: 192.168.2.59
    version: 5
    port: 8899
    groups:
    - number: 1
      type: rgbw
      name: Bedroom Lamp
    - number: 2
      type: white
      name: Living Room Fan Light
      #- number: 3
      #type: white
      #name: Group 3
    - number: 4
      type: rgbw
      name: Living Room Lamps
