# Multi-Room
- platform: mpd
  host: localhost
  port: 6601
  location: Multi-Room Audio
# Room Audio
#- platform: mpd
#  server: bedroom
#  location: Bedroom
#- platform: mpd
#  server: craftroom
#  location: Craft Room
#- platform: mpd
#  server: automation
#  location: Living Room
# TV devices
- platform: cast
- platform: firetv
  host: localhost
- platform: snapcast
  host: localhost
  play_media_source: 'TTS'
  play_media_command: 'ffmpeg -y -i {} -f u16le -acodec pcm_s16le -ac 2 -ar 48000 /tmp/snapcast_tts'
