#  Set up a notification platform so that alerts from
#  Home Assistant can be received in the browser on a mobile device.

- platform: group
  name: all
  services:
    - service: html5
- platform: group
  name: her
  services:
  - service: html5
- platform: group
  name: him
  services:
  - service: pushbullet
- platform: pushbullet
  name: pushbullet
  api_key: !secret pushbullet_api_key
- platform: html5
  name: html5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id
