alias: Turn on lights when anyone gets home
trigger:
  platform: state
  entity_id:
  - device_tracker.his_phone
  - device_tracker.her_phone
  state: 'home'
condition:
- condition: state
  entity_id: switch.presence
  state: 'on'
- condition: state
  entity_id: switch.sleep
  state: 'off'
- condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 5
action:
  - service: switch.turn_on
    entity_id:
    - switch.unknown_id000c_unknown_type4447_id3033_switch_14_0
    - switch.unknown_id000c_unknown_type4447_id3033_switch_15_0
