alias: Turn on lights when anyone gets home
trigger:
  platform: state
  entity_id:
    - group.all_devices
  to: 'home'
condition:
- condition: state
  entity_id: switch.presence
  state: 'on'
- condition: state
  entity_id: switch.sleep
  state: 'off'
- condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 10
action:
  - service: switch.turn_on
    entity_id:
    - switch.zwave_switch_2_switch
    - switch.zwave_switch_3_switch
