#  Turn the lights on at sunset.

alias: Turn on light when sun sets
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 0
condition:
- condition: state
  entity_id: switch.presence
  state: 'on'
- condition: state
  entity_id: group.all_devices
  state: 'home'
- condition: state
  entity_id: switch.vacation
  state: 'off'
action:
  service: light.turn_on
  entity_id:
    - switch.zwave_switch_4_switch
    - light.zwave_dimmer_1_level
