alias: Record which location a person was at
trigger:
  platform: state
  entity_id:
  - device_tracker.his_phone
  - device_tracker.her_phone
  to: 'not_home'
action:
  service: mqtt.publish
  data_template:
    payload_template: '{{trigger.from_state.state}}'
    topic: 'home/last_location/{{trigger.entity_id}}'
