#  Don't leave the lights on when no one is home!
#  But only turn them off if there are no guests present.
#  Note that `group.all_devices` is special: Its state
#  is 'home' if ANY tracked device is home, and 'not_home'
#  if EVERY tracked device is not home.

alias: Turn off things when everyone leaves
trigger:
  platform: state
  entity_id: group.all_devices
  to: 'not_home'
condition:
- condition: state
  entity_id: switch.presence
  state: 'on'
- condition: state
  entity_id: switch.guests
  state: 'off'
action:
- service: light.turn_off
  entity_id: group.all_lights
- service: lock.lock
  entity_id: group.all_locks
- service: fan.turn_off
  entity_id: group.all_fans
- service: switch.turn_off
  entity_id:
    - switch.zwave_switch_1_switch
    - switch.zwave_switch_2_switch
    - switch.zwave_switch_3_switch
    - switch.zwave_switch_4_switch
    - switch.zwave_switch_5_switch
    - switch.zwave_switch_6_switch
    - switch.zwave_switch_7_switch
- service: climate.set_away_mode
  data:
    entity_id: climate.thermostat
    away_mode: true
