#  Point the camera according to a preset view
#  configured on the camera.
#  There is one shell command (curl) configured
#  per preset. This automation checks the value of
#  the associated input selector and fires the
#  appropriate shell command.

alias: Camera preset control
trigger:
- platform: state
  entity_id: input_select.cam_preset
action:
  service_template: >
    shell_command.cam_preset_{{states.input_select.cam_preset.state.lower().replace(" ", "_")}}
