alias: Turn on den lights via IR
trigger:
  platform: mqtt
  topic: lirc/status/insig/KEY_0
action:
  - service: light.toggle
    entity_id: 
    - light.living_room_lamps
    - light.living_room_fan_light
