alias: Alert if the front door was left open
trigger:
  platform: state
  entity_id: sensor.door_two
  state: 'off'
  for:
    seconds: 120
action:
  - service: notify.all
    data_template:
      message: 'Front door is open! Please close it.'
