alias: Alert if the side door was left open
trigger:
  platform: state
  entity_id: binary_sensor.door_one
  state: 'on'
  for:
    seconds: 120
action:
  - service: notify.all
    data_template:
      message: 'Side door is open! Please close it.'
