#  Executes Powershell scripts remotely
#  via HTTP API for remote Windows PC
#  control.
#
#  https://blogs.msdn.microsoft.com/powershell/2014/09/29/simple-http-api-for-executing-powershell-scripts/

- platform: command_line
  switches:
    sound:
      command_on: !env_var PC_SOUND_TOGGLE
      command_off: !env_var PC_SOUND_TOGGLE
    monitors:
      command_on: !env_var PC_MONITORS_ON
      command_off: !env_var PC_MONITORS_OFF
- platform: wake_on_lan
  mac_address: !env_var PC_MAC_ADDRESS
  name: "Turn On PC"
  host: !env_var PC_IP_ADDRESS
