#########################################################################
# Cameras
#
#  Camera management.
#########################################################################

homeassistant:
  customize:
    script.cam_up:
      icon: mdi:arrow-up
      friendly_name: Camera Up
    script.cam_down:
      icon: mdi:arrow-down
      friendly_name: Camera Down
    script.cam_left:
      icon: mdi:arrow-left
      friendly_name: Camera Left
    script.cam_right:
      icon: mdi:arrow-right
      friendly_name: Camera Right
    script.cam_ir_on:
      hidden: true
    script.cam_ir_off:
      hidden: true
    switch.cam_ir:
      friendly_name: 'Camera IR'
      assumed_state: true
      icon: mdi:eye
    camera.camera:
      friendly_name: Front
  customize_glob:
    'sensor.*_audio_connections':
      hidden: true
    'sensor.*_video_connections':
      hidden: true

# Group camera entities.
group:
  Camera:
    - camera.camera
    #- camera.last_motion
    - binary_sensor.cam_motion
    - script.cam_up
    - script.cam_down
    - script.cam_left
    - script.cam_right
    - switch.cam_ir
    - camera.den
    - camera.kitchen
    - camera.backyard
 
# Set up Android phone webcams.
android_ip_webcam:
  #  - host: !secret android_ip_1
  #  scan_interval: 20
  #  name: Kitchen
  #  motion_sensor: true
  #  sensors:
  #    - battery_level
  #    - light
  #    - sound
  - host: !secret android_ip_2
    scan_interval: 20
    name: Den
    motion_sensor: true
    sensors:
      - battery_level
      - light
      - sound

# Set up standard security webcam.
camera:
  - platform: generic
    still_image_url: !secret cam_image_url
    name: Camera
#  - platform: ffmpeg
#    input: !secret wansview_rtsp
#    name: Backyard

# Script that relays camera commands.
shell_command:
  cam_direction: !secret cam_direction_script

# IR can be turned on and off. Represent this as
# a switch in the UI by linking the on and off
# functions to the corresponding script.
switch:
  - platform: template
    switches:
      cam_ir:
        value_template: "off"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.cam_ir_on
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.cam_ir_off

script:
  # Send a command to rotate the camera down.
  cam_down:
    sequence:
      - service: shell_command.cam_direction
        data:
          direction: 'down'
  # Send a command to rotate the camera up.
  cam_up:
    sequence:
      - service: shell_command.cam_direction
        data:
          direction: 'up'
  # Send a command to rotate the camera left.
  cam_left:
    sequence:
      - service: shell_command.cam_direction
        data:
          direction: 'left'
  # Send a command to rotate the camera right.
  cam_right:
    sequence:
      - service: shell_command.cam_direction
        data:
          direction: 'right'
  # Send a command to turn IR on.
  cam_ir_on:
    sequence:
      - service: shell_command.cam_direction
        data:
          direction: 'ir_on'
  # Send a command to turn IR off.
  cam_ir_off:
    sequence:
      - service: shell_command.cam_direction
        data:
          direction: 'ir_off'
