#########################################################################
# Cats
#
#  Sorry, cats can't be automated.
#########################################################################

homeassistant:
  customize:
    sensor.litter_box:
      icon: mdi:emoticon-poop

sensor:
  - platform: mqtt
    state_topic: "home/scale/state"
    name: "Litter Box"
    unit_of_measurement: "g"

automation:
  # Announce over TTS when the cat door is opened.
  - alias: Announce when cat door is opened
    trigger:
      platform: state
      entity_id: binary_sensor.door_five
      from: 'off'
      to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.play_tts
        data:
          variables:
            message: "The cat door was opened."
  # Announce over TTS when the cat door is closed.
  - alias: Announce when cat door is closed
    trigger:
      platform: state
      entity_id: binary_sensor.door_five
      from: 'on'
      to: 'off'
    action:
      - service: script.turn_on
        entity_id: script.play_tts
        data:
          variables:
            message: "The cat door is now closed."
  # Text a warning if the cat door is open and no one is home.
  - alias: Warn if cat door is open when not home
    trigger:
      platform: state
      entity_id: group.tracked_people
      from: 'home'
      to: 'not_home'
    condition:
      condition: state
      entity_id: binary_sensor.door_five
      state: 'on'
    action:
      - service: notify.all
        data_template:
          message: "You left the cat door open. Better go back and close it!"
