homeassistant:
  customize:
    weather.thermostat:
      hidden: true
    sensor.low_target:
      icon: mdi:format-vertical-align-bottom
    sensor.high_target:
      icon: mdi:format-vertical-align-top
    sensor.thermostat_temperature:
      friendly_name: Foyer Temperature

sensor:
  - platform: template
    sensors:
      low_target:
        friendly_name: "Minimum Temperature"
        value_template: "{{states.climate.thermostat.attributes.target_temp_low}}"
      high_target:
        friendly_name: "Maximum Temperature"
        value_template: "{{states.climate.thermostat.attributes.target_temp_high}}"


group:
  Temperatures:
    - sensor.kitchen_temperature
    - sensor.den_temperature
    - sensor.bedroom_temperature
    - sensor.thermostat_temperature
    - sensor.high_target
    - sensor.low_target


ecobee:
  api_key: !secret ecobee_api_key

automation:
  - alias: turn on away mode when everyone leaves
    trigger:
      - platform: state
        entity_id: group.tracked_people
        to: not_home
    condition:
      - condition: state
        entity_id: switch.guests
        state: 'off'
    action:
      - service: fan.turn_off
        entity_id: group.all_fans
      - service: climate.set_away_mode
        data:
          entity_id: climate.thermostat
          away_mode: true

  - alias: turn off away mode
    trigger:
      - platform: state
        entity_id: group.tracked_people
        to: home
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.thermostat
          away_mode: false

  - alias: turn on fan while sleeping
    trigger:
      - platform: numeric_state
        entity_id: sensor.dark_sky_temperature
        above: 60
    condition:
      - condition: state
        entity_id: switch.sleeping
        state: 'on'
    action:
      - service: fan.turn_on
        entity_id: fan.zwave_fan_1_level
        data:
          speed: 'low'

  - alias: turn off fan while sleeping
    trigger:
      - platform: numeric_state
        entity_id: sensor.dark_sky_temperature
        above: 60
    condition:
      - condition: state
        entity_id: switch.sleeping
        state: 'on'
    action:
      - service: fan.turn_off
        entity_id: fan.zwave_fan_1_level
