homeassistant:
  customize:
    sensor.deliveries_today:
      icon: mdi:package-variant
    sensor.packages_in_transit:
      icon: mdi:truck-delivery

group:
  Deliveries:
    - sensor.usps_mail
    - sensor.usps_packages
    - sensor.ups
    - sensor.fedex
    - sensor.deliveries_today
    - sensor.packages_in_transit
    - camera.usps_mail

#usps:
#  username: !secret myusps_username
#  password: !secret myusps_password
#  name: 'USPS'

sensor:
  - platform: ups
    name: 'UPS'
    username: !secret upsmychoice_username
    password: !secret upsmychoice_password
#  - platform: fedex
#    name: 'Fedex'
#    username: !secret fedexdeliverymanager_username
#    password: !secret fedexdeliverymanager_password
  - platform: template
    sensors:
      packages_in_transit:
        friendly_name: "Packages in Transit"
        value_template: >
          {% macro in_transit(sensor) %}
            {% if sensor %}
              {{sensor.state|int - delivered(sensor)|int}}
            {% else %}
              0
            {% endif %}
          {% endmacro %}
          {% macro delivered(sensor) %}
            {% if 'delivered' in sensor.attributes %}
              {{sensor.attributes.delivered}}
            {% else %}
               0
            {% endif %}
          {% endmacro %}
          {{in_transit(states.sensor.usps_packages)|int + in_transit(states.sensor.ups)|int + in_transit(states.sensor.fedex)|int}}
      deliveries_today:
        friendly_name: "Today's Deliveries"
        value_template: >
          {% macro delivered(sensor) %}
            {% if 'delivered' in sensor.attributes %}
              {{sensor.attributes.delivered}}
            {% else %}
               0
            {% endif %}
          {% endmacro %}
          {{delivered(states.sensor.usps_packages)|int + delivered(states.sensor.ups)|int + delivered(states.sensor.fedex)|int}}

automation:
  - alias: USPS delivery notification
    trigger:
      platform: event
      event_type: mailgun_message_received
      event_data:
        from: !secret usps_sender
    condition:
      - condition: state
        entity_id: switch.sleeping
        state: 'off'
      - condition: template
        value_template: '{{"Delivered" in trigger.event.data.subject}}'
    action:
      - service: persistent_notification.create
        data_template:
          title: '{{trigger.event.data.subject.split("for")[0]}}'
          message: '{{trigger.event.data.subject.split("for")[0]}}'
      - service: script.turn_on
        entity_id: script.play_tts
        data_template:
          variables:
            message: '{{trigger.event.data.subject.split("for")[0]}}'
  - alias: Fedex delivery notification
    trigger:
      platform: event
      event_type: mailgun_message_received
      event_data:
        from: !secret fedex_sender
    condition:
      - condition: state
        entity_id: switch.sleeping
        state: 'off'
      - condition: template
        value_template: '{{"been delivered" in trigger.event.data.subject}}'
    action:
      - service: persistent_notification.create
        data_template:
          title: 'Fedex package delivered'
          message: '{{trigger.event.data.subject}}'
      - service: script.turn_on
        entity_id: script.play_tts
        data_template:
          variables:
            message: 'Fedex package delivered'
  - alias: UPS delivery notification
    trigger:
      platform: event
      event_type: mailgun_message_received
      event_data:
        from: !secret ups_sender
    condition:
      - condition: state
        entity_id: switch.sleeping
        state: 'off'
      - condition: template
        value_template: '{{"was delivered" in trigger.event.data.subject}}'
    action:
      - service: persistent_notification.create
        data_template:
          title: 'UPS package delivered'
          message: '{{trigger.event.data.subject}}'
      - service: script.turn_on
        entity_id: script.play_tts
        data_template:
          variables:
            message: 'UPS package delivered'
