#########################################################################
# Doorbell
#
#  Configuration for doorbell integration. The doorbell button is wired
#  directly to the pins of a NodeMCU. When pressed, it sends an MQTT
#  message.
#########################################################################

homeassistant:
  customize:
    script.play_chime:
      friendly_name: Play Chime
      icon: mdi:bell-ring
    counter.chime_counter:
      friendly_name: Chime Count
      unit_of_measurement: 'presses'

# Group the doorbell entities.
group:
  Doorbell:
    - script.play_chime
    - counter.chime_counter
    - binary_sensor.doorbell_online

# Maintain a counter of doorbell presses.
counter:
  chime_counter:
    name: Chime Count

# Track connectivity of doorbell NodeMCU.
binary_sensor:
  - platform: mqtt
    name: "Doorbell Online"
    state_topic: "home/doorbell/online"
    payload_on: "yes"
    payload_off: "no"
    device_class: "connectivity"

automation:
  # Handle doorbell presses, if we're not sleeping.
  - alias: Announce doorbell presses
    trigger:
      platform: mqtt
      topic: 'home/doorbell/pressed'
      payload: 'yes'
    condition:
      - condition: state
        entity_id: switch.sleeping
        state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.play_chime
  # The notification sent on a press gives an option to turn
  # on the lights. Watch for that request.
  - alias: Turn on Porch Lights from Notification
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: turn_on_porch_lights
    action:
      - service: switch.turn_on
        entity_id:
          - switch.zwave_switch_2_switch
          - switch.zwave_switch_3_switch

script:
  # Chime sequence. Increment the chime counter, play the chime
  # over the multi-room audio system (pausing music if necessary),
  # and send a notification with a snapshot from porch-facing camera,
  # with an option to turn on porch lights.
  play_chime:
    sequence:
      - service: counter.increment
        data:
          entity_id: counter.chime_counter
      - service: notify.all
        data_template:
          message: 'Doorbell rang'
          data:
            image: !secret front_camera_snapshot_url
            url: !secret front_camera_stream_url
            tag: doorbell_rang
            actions:
              - action: turn_on_porch_lights
                title: 'Turn On Porch Lights'
      - service: media_player.snapcast_snapshot
        data:
          entity_id:
            - !secret snapcast_group_1
            - !secret snapcast_hifiberry1
            - !secret snapcast_hifiberry2
            - !secret snapcast_raspberrypi
      - service: media_player.select_source
        data:
          entity_id: !secret snapcast_group_1
          source: TTS
      - service: media_player.volume_set
        data:
          entity_id:
            - !secret snapcast_hifiberry1
            - !secret snapcast_hifiberry2
            - !secret snapcast_raspberrypi
          volume_level: 1.0
      - service: media_player.play_media
        data:
          entity_id: media_player.mpd
          media_content_id: !secret doorbell_mp3
          media_content_type: 'music'
      - wait_template: "{{states.media_player.mpd.state == 'off'}}"
        timeout: 120
      - service: media_player.snapcast_restore
        data:
          entity_id:
            - !secret snapcast_group_1
            - !secret snapcast_hifiberry1
            - !secret snapcast_hifiberry2
            - !secret snapcast_raspberrypi
