automation:
  - alias: Announce doorbell presses
    trigger:
      platform: mqtt
      topic: 'home/doorbell/pressed'
      payload: 'yes'
    action:
      - service: switch.turn_on
        entity_id: switch.unknown_id000c_unknown_type4447_id3033_switch_14_0
      - service: media_player.play_media
        data:
          entity_id: media_player.tts
          media_content_id: !secret doorbell_mp3
          media_content_type: 'music'
      - service: notify.all
        data_template:
          message: 'Someone rang the doorbell.'
