automation:
  - alias: Announce doorbell presses
    trigger:
      platform: mqtt
      topic: 'home/doorbell/pressed'
      payload: 'yes'
    action:
      - service: switch.turn_on
        entity_id: switch.unknown_id000c_unknown_type4447_id3033_switch_14_0
      - service: tts.amazon_polly_say
        data_template:
          entity_id: media_player.tts
          message: 'Someone rang the doorbell.'
      - service: notify.all
        data_template:
          message: 'Someone rang the doorbell.'
