automation:
  - alias: Announce doorbell presses
    trigger:
      platform: mqtt
      topic: 'home/doorbell/pressed'
      payload: 'yes'
    action:
      - service: script.turn_on
        entity_id: script.play_chime

script:
  play_chime:
    sequence:
      - service: snapcast.snapcast_snapshot
        data:
          entity_id:
            - media_player.snapcast_group_12a48ec83a0f70ea581539a0763918b6
            - media_player.snapcast_client_b827ebc8b2f8
      - service: media_player.select_source
        data:
          entity_id: media_player.snapcast_group_12a48ec83a0f70ea581539a0763918b6
          source: TTS
      - service: media_player.volume_set
        data:
          entity_id: media_player.snapcast_client_b827ebc8b2f8
          volume_level: 1.0
      - service: media_player.play_media
        data:
          entity_id: media_player.tts
          media_content_id: !secret doorbell_mp3
          media_content_type: 'music'
      - delay:
          seconds: 1
      - wait_template: "{{states.media_player.tts.state == 'idle'}}"
        timeout: 120
      - delay:
          seconds: 1
      - service: snapcast.snapcast_restore
        data:
          entity_id:
            - media_player.snapcast_group_12a48ec83a0f70ea581539a0763918b6
            - media_player.snapcast_client_b827ebc8b2f8
