#########################################################################
# Home Assistant
#
#  Manage meta-switches and Home Assistant-specific states.
#########################################################################

homeassistant:
  customize:
    switch.alert_delays:
      icon: mdi:car
    sensor.new_commits:
      icon: mdi:github-circle
    sensor.home_assistant_errors:
      icon: mdi:alert-circle
    sensor.home_assistant_warnings:
      icon: mdi:alert-circle-outline
    sensor.connected_clients:
      icon: mdi:account-multiple

# Group meta entities.
group:
  Home Assistant:
    - switch.alert_delays
    - sensor.connected_clients
    - sensor.home_assistant_errors
    - sensor.home_assistant_warnings
    - sensor.uptime
    - sensor.new_commits

sensor:
  # Since we run the "dev" branch, see how many new commit there are.
  - platform: command_line
    name: New Commits
    scan_interval: 600
    unit_of_measurement: commits
    command: "git fetch origin && git log dev..origin/dev --pretty=oneline | wc -l"
  # Track how many errors are in the log.
  - platform: command_line
    name: Home Assistant Errors
    scan_interval: 30
    unit_of_measurement: errors
    command: !secret ha_error_command
  # Track how many warnings are in the log.
  - platform: command_line
    name: Home Assistant Warnings
    scan_interval: 30
    unit_of_measurement: warnings
    command: !secret ha_warning_command
  # Track Home Assistant uptime.
  - platform: uptime
    unit_of_measurement: hours
  # Track number of connected clients.
  - platform: api_streams

switch:
  # Enable/Disable delay alerts.
  - platform: mqtt
    name: "Alert Delays"
    state_topic: "nfc/alert_delays"
    command_topic: "nfc/alert_delays"
    qos: 1
    payload_on: "yes"
    payload_off: "no"
    retain: true
