homeassistant:
  customize:
    script.living_room_lights:
      emulated_hue_hidden: True
      emulated_hue_name: 'Living Room Lights'

script:
  living_room_lights:
    sequence:
      - service: light.toggle
        entity_id:
          - light.living_room_lamps
          - light.living_room_fan_light
          - switch.zwave_switch_7_switch

automation:
  - alias: Bedroom light occupancy
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_occupancy
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.bedroom_lamp
          - light.zwave_dimmer_2_level
  - alias: Den light occupancy
    trigger:
      - platform: state
        entity_id: binary_sensor.den_occupancy
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.zwave_dimmer_1_level
  - alias: Kitchen light occupancy
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupancy
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.zwave_switch_1_switch
          - switch.zwave_switch_3_switch
  - alias: Turn various lights after dark when door opens
    trigger:
      platform: state
      entity_id: binary_sensor.door_two
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 5
    action:
      - service: switch.turn_on
        entity_id:
          - switch.zwave_switch_3_switch
          - switch.zwave_switch_1_switch
          - switch.zwave_switch_6_switch
          - switch.zwave_switch_7_switch
