#########################################################################
# Lights
#
#  Handle everything primarily lighting-related.
#########################################################################

homeassistant:
  customize:
    group.living_room:
      emulated_hue_hidden: false
      emulated_hue_name: 'Living Room Lights'

group:
  # Group switched lighting together.
  Switched Lighting:
    - switch.zwave_switch_1_switch
    - switch.zwave_switch_4_switch
    - switch.zwave_switch_7_switch
    - switch.zwave_switch_3_switch
    - switch.zwave_switch_2_switch
    - switch.zwave_switch_6_switch
    - switch.zwave_switch_5_switch
  # Group dimmable lighting together.
  Dimmable Lighting:
    - light.bedroom_lamp
    - light.zwave_dimmer_2_level
    - light.zwave_dimmer_3_level
    - light.zwave_dimmer_1_level
    - light.living_room_lamps
    - light.living_room_fan_light
    - light.stair_lighting
  # Master lighting group with switched and dimmable lighting.
  All Lighting:
    - group.switched_lighting
    - group.dimmable_lighting

automation:
  # The living room has several lamps and overhead lights. When the wall
  # switch is double-tapped on, turn on all the lighting (rather then the single
  # pair of lights physicallly wired to the switch).
  - alias: Living Room Scene On
    trigger:
      - event_type: zwave.scene_activated
        platform: event
        event_data:
          entity_id: zwave.zwave_switch_7
          scene_id: 1
          scene_data: 3
    action:
      - service: light.turn_on
        entity_id:
          - light.living_room_lamps
          - light.living_room_fan_light
      - service: switch.turn_on
        entity_id:
          - switch.zwave_switch_7_switch

  # Turn off all the lights when the switched is double-tapped off.
  - alias: Living Room Scene Off
    trigger:
      - event_type: zwave.scene_activated
        platform: event
        event_data:
          entity_id: zwave.zwave_switch_7
          scene_id: 2
          scene_data: 3
    action:
      - service: light.turn_off
        entity_id:
          - light.living_room_lamps
          - light.living_room_fan_light
      - service: switch.turn_off
        entity_id:
          - switch.zwave_switch_7_switch

  # The stairs have LED lighting, unconnected to a physical switch.
  # Turn it on when the overhead lighting switch is double-tapped on.
  - alias: Stair Scene On
    trigger:
      - event_type: zwave.scene_activated
        platform: event
        event_data:
          entity_id: zwave.zwave_switch_6
          scene_id: 1
          scene_data: 3
    action:
      - service: light.turn_on
        entity_id: light.stair_lighting
        data:
          brightness: 50
          color_name: white

  # Turn off the stair LED lighting when the overhead lighting switch
  # is double-tapped off.
  - alias: Stairs Scene Off
    trigger:
      - event_type: zwave.scene_activated
        platform: event
        event_data:
          entity_id: zwave.zwave_switch_6
          scene_id: 2
          scene_data: 3
    action:
      - service: light.turn_off
        entity_id: light.stair_lighting

  # Turn on dim red night-lighting on the stair LEDs
  # when the overhead lighting physical switch is
  # triple-tapped on.
  - alias: Stair Scene On (Red)
    trigger:
      - event_type: zwave.scene_activated
        platform: event
        event_data:
          entity_id: zwave.zwave_switch_6
          scene_id: 1
          scene_data: 4
    action:
      - service: light.turn_on
        entity_id: light.stair_lighting
        data:
          brightness: 10
          color_name: red

  # Turn off stair LEDs when the overhead lighting physical
  # switch is triple-tapped off.
  - alias: Stair Scene Off (Red)
    trigger:
      - event_type: zwave.scene_activated
        platform: event
        event_data:
          entity_id: zwave.zwave_switch_6
          scene_id: 2
          scene_data: 4
    action:
      - service: light.turn_off
        entity_id: light.stair_lighting

  # Turn on the bedroom light at the dimmest setting
  # when the switch is double-tapped on.
  - alias: Gentle bedroom light
    trigger:
      - event_type: zwave.scene_activated
        platform: event
        event_data:
          entity_id: zwave.zwave_dimmer_2
          scene_id: 1
          scene_data: 3
    action:
      - service: light.turn_on
        entity_id: light.zwave_dimmer_2_level
        data:
          brightness: 5

  # Automatically turn off the bedroom light when
  # the occupancy sensor goes off.
  - alias: Bedroom light occupancy
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_occupancy
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.bedroom_lamp
          - light.zwave_dimmer_2_level

  # Automatically turn off the den light when
  # the occupancy sensor goes off.
  - alias: Den light occupancy
    trigger:
      - platform: state
        entity_id: binary_sensor.den_occupancy
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.zwave_dimmer_1_level

  # Automatically turn off the kitchen lights when
  # the occupancy sensor goes off.
  - alias: Kitchen light occupancy
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupancy
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.zwave_switch_1_switch
          - switch.zwave_switch_3_switch

  # If it's dark outside in the evening and the front door
  # is opened, turn on the foyer lights, porch lights,
  # and stair LED lighting.
  - alias: Turn various lights after dark when door opens
    trigger:
      platform: state
      entity_id: binary_sensor.door_two
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 5
      - condition: time
        after: '12:00:00'
    action:
      - service: switch.turn_on
        entity_id:
          - switch.zwave_switch_3_switch
          - switch.zwave_switch_2_switch
      - service: light.turn_on
        entity_id:
          - light.stair_lighting
        data:
          brightness: 50
          color_name: white

  # If it is dark outside (either sun is going down, or significant
  # cloud coverage), turn on the porch lanterns.
  - alias: turn on porch light
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{state.attributes.elevation}}'
        below: 15
      - platform: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        above: 80
    action:
      service: switch.turn_on
      entity_id: switch.zwave_switch_2_switch

  # Turn off the porch light if it's light outside, except
  # if there's a lot of cloud coverage.
  - alias: turn off porch light
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{state.attributes.elevation}}'
        above: 15
    condition:
      - condition: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        below: 80
    action:
      service: switch.turn_off
      entity_id: switch.zwave_switch_2_switch

  # If all tracked occupants have left, and there's no guests,
  # turn off all the house lights.
  - alias: turn off lights when house is empty
    trigger:
      - platform: state
        entity_id: group.tracked_people
        to: not_home
    condition:
      - condition: state
        entity_id: switch.guests
        state: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: group.all_lighting
