homeassistant:
  customize:
    script.all_rooms_audio:
      friendly_name: Spotify Everywhere
      icon: mdi:spotify
      emulated_hue: true
    media_player.spotify:
      emulated_hue: true
      emulated_hue_name: speakers

group:
  Snapclients:
    - media_player.snapcast_client_74da3868e5f1
    - media_player.snapcast_client_b827ebc8b2f8
    - media_player.snapcast_group_2460d731f12d94d93ddfb2dc77969fac
    - script.all_rooms_audio

#panel_iframe:
#  audio:
#    title: Multi-Room Audio
#    icon: mdi:music-box-outline
#    url: !secret audio_url

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: !secret aws_region
  - platform: voicerss
    api_key: !secret voicerss_api_key

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

media_player:
  - platform: snapcast
    host: localhost
#  - platform: gstreamer
#    name: 'TTS'
#    pipeline: 'audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapcast_tts'
  - platform: ffmpeg
    name: 'TTS'
    output: "- > /tmp/snapcast_tts"
    extra_arguments: "-f u16le -acodec pcm_s16le -ac 2 -ar 48000"
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

script:
  all_rooms_audio:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.spotify
          source: 'Multi-Room Audio'
      - service: media_player.select_source
        data:
          entity_id: media_player.snapcast_group_2460d731f12d94d93ddfb2dc77969fac
          source: 'Spotify'
      - service: switch.turn_on
        data:
          entity_id: switch.hdmi_5
      - service: hdmi_cec.select_device
        data:
          device: '1.2.0.0'
      - service: input_select.select_option
        data:
          entity_id: input_select.tv_input
          option: 'Multi-Room Audio'
  play_tts:
    sequence:
      - service: snapcast.snapcast_snapshot
        data:
          entity_id:
            - media_player.snapcast_group_2460d731f12d94d93ddfb2dc77969fac
            - media_player.snapcast_client_b827ebc8b2f8
      - service: media_player.select_source
        data:
          entity_id: media_player.snapcast_group_2460d731f12d94d93ddfb2dc77969fac
          source: TTS
      - service: media_player.volume_set
        data:
          entity_id: media_player.snapcast_client_b827ebc8b2f8
          volume_level: 0.5
      - service_template: "tts.{{states.input_select.tts_engine.state}}_say"
        data_template:
          entity_id: media_player.tts
          message: "{{message}}"
      - wait_template: "{{states.media_player.tts.state == 'idle'}}"
        timeout: 120
      - service: snapcast.snapcast_restore
        data:
          entity_id:
            - media_player.snapcast_group_2460d731f12d94d93ddfb2dc77969fac
            - media_player.snapcast_client_b827ebc8b2f8

automation:
  - alias: Multi-Room Audio Pause
    trigger:
      platform: mqtt
      topic: lirc/status/insig/KEY_PAUSE
      payload: '0'
    action:
      service_template: media_player.media_pause
      entity_id: media_player.multiroom_audio
  - alias: Multi-Room Audio Play
    trigger:
      platform: mqtt
      topic: lirc/status/insig/KEY_PLAY
      payload: '0'
    action:
      service_template: media_player.media_play
      entity_id: media_player.multiroom_audio
