homeassistant:
  customize_glob:
    sensor.canon_ix6800:
      friendly_name: Printer
    'sensor.pihole_*':
      icon: mdi:block-helper
    sensor.speedtest_download:
      icon: mdi:download
      friendly_name: Download
    sensor.speedtest_upload:
      icon: mdi:upload
      friendly_name: Upload
    sensor.speedtest_ping:
      icon: mdi:timer
      friendly_name: Ping

group:
  Network:
    - sensor.speedtest_upload
    - sensor.speedtest_download
    - sensor.speedtest_ping
    - sensor.canon_ix6800
    - sensor.pihole_ads_blocked_today
    - sensor.pihole_ads_percentage_blocked_today
    - sensor.pihole_dns_queries_today
    - weblink.router

panel_iframe:
  dns:
    title: DNS
    icon: mdi:block-helper
    url: !secret pi_hole_url

sensor:
  - platform: pi_hole
    scan_interval: 600
    host: localhost:8032
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: cups
    printers:
      - Canon_iX6800
