homeassistant:
  customize:
    - entity_id: sensor.air_quality_numeric
      hidden: true
    - entity_id: sensor.air_quality
      icon: mdi:cloud-check
    - entity_id: sun.sun
      icon: mdi:weather-sunny
    - entity_id: sensor.dark_sky_humidity
      icon: mdi:water-percent
      friendly_name: Humidity
    - entity_id: sensor.dark_sky_temperature
      icon: mdi:thermometer
      friendly_name: Temperature
    - entity_id: sensor.dark_sky_summary
      icon: mdi:leaf
      friendly_name: Conditions
    - entity_id: sensor.dark_sky_cloud_coverage
      friendly_name: Cloud Coverage
    - entity_id: sensor.dark_sky_daily_high_temperature
      hidden: true
    - entity_id: sensor.dark_sky_daily_low_temperature
      hidden: true
    - entity_id: sensor.dark_sky_daily_summary
      hidden: true
    - entity_id: sensor.dark_sky_hourly_summary
      hidden: true
    - entity_id: sensor.waqi*
      hidden: true

group:
  Outdoors:
    - sensor.dark_sky_summary
    - sun.sun
    - sensor.dark_sky_temperature
    - sensor.dark_sky_humidity
    - sensor.dark_sky_cloud_coverage
    - sensor.air_quality
    - camera.weather_radar

camera:
  - platform: generic
    still_image_url: !secret weather_map_url
    name: Weather Radar

sensor:
  - platform: waqi
    locations:
    - !secret waqi_location
  - platform: template
    sensors:
      air_quality_numeric:
        value_template: !secret air_quality_sensor_template
      air_quality:
        friendly_name: 'Air Quality'
        value_template: >
          {% if states.sensor.air_quality_numeric.state|int <= 50 %}
            Good
          {% elif states.sensor.air_quality_numeric.state|int <= 100 %}
            Moderate
          {% elif states.sensor.air_quality_numeric.state|int <= 150 %}
            Unhealthy
          {% endif %}
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - temperature
      - humidity
      - hourly_summary
      - daily_summary
      - cloud_cover
      - temperature_max
      - temperature_min
