homeassistant:
  customize:
    sensor.air_quality_numeric:
      hidden: true
    sensor.air_quality:
      icon: mdi:cloud-check
    sun.sun:
      icon: mdi:weather-sunny
    sensor.dark_sky_humidity:
      icon: mdi:water-percent
      friendly_name: Humidity
    sensor.dark_sky_temperature:
      icon: mdi:thermometer
      friendly_name: Temperature
    sensor.dark_sky_summary:
      icon: mdi:leaf
      friendly_name: Conditions
    sensor.dark_sky_cloud_coverage:
      friendly_name: Cloud Coverage
    sensor.dark_sky_daily_high_temperature:
      hidden: true
    sensor.dark_sky_daily_low_temperature:
      hidden: true
    sensor.dark_sky_daily_summary:
      hidden: true
    sensor.dark_sky_hourly_summary:
      hidden: true
    sensor.moon:
      icon: mdi:vector-circle-variant
  customize_glob:
    'sensor.waqi*':
      hidden: true

group:
  Outdoors:
    - sensor.dark_sky_summary
    - sun.sun
    - sensor.dark_sky_temperature
    - sensor.dark_sky_humidity
    - sensor.dark_sky_cloud_coverage
    - sensor.air_quality
    - sensor.moon
    - camera.weather_radar

camera:
  - platform: generic
    still_image_url: !secret weather_map_url
    name: Weather Radar

sensor:
  - platform: moon
  - platform: waqi
    token: !secret waqi_token
    locations:
    - !secret waqi_location
  - platform: template
    sensors:
      air_quality_numeric:
        value_template: !secret air_quality_sensor_template
      air_quality:
        friendly_name: 'Air Quality'
        value_template: >
          {% if states.sensor.air_quality_numeric.state|int <= 50 %}
            Good
          {% elif states.sensor.air_quality_numeric.state|int <= 100 %}
            Moderate
          {% elif states.sensor.air_quality_numeric.state|int <= 150 %}
            Unhealthy
          {% endif %}
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - temperature
      - humidity
      - hourly_summary
      - daily_summary
      - cloud_cover
      - temperature_max
      - temperature_min
