homeassistant:
  customize:
    switch.sleeping:
      icon: mdi:sleep
      emulated_hue_hidden: true
      emulated_hue_name: Sleep Mode
    switch.vacation:
      icon: mdi:airplane
    switch.guests:
      icon: mdi:human-male-female

group:
  People:
    - device_tracker.his_phone
    - device_tracker.her_phone
    - switch.sleeping
    - switch.vacation
    - switch.guests

switch:
  - platform: mqtt
    name: "Sleeping"
    state_topic: "nfc/sleeping"
    command_topic: "nfc/sleeping"
    qos: 1
    payload_on: "yes"
    payload_off: "no"
    retain: true
  - platform: mqtt
    name: "Vacation"
    state_topic: "nfc/vacation"
    command_topic: "nfc/vacation"
    qos: 1
    payload_on: "yes"
    payload_off: "no"
    retain: true
  - platform: mqtt
    name: "Guests"
    state_topic: "nfc/guests"
    command_topic: "nfc/guests"
    qos: 1
    payload_on: "yes"
    payload_off: "no"
    retain: true

automation:
  - alias: Vacation started
    trigger:
      platform: state
      entity_id: switch.vacation
      to: 'on'
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.thermostat
          away_mode: true
  - alias: Sleeping
    trigger:
      platform: state
      entity_id: switch.sleeping
      to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.any_door_open
        state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.play_tts
        data_template:
          variables:
            message: "Good night."
      - service: light.turn_off
        entity_id: group.all_lights
      - service: switch.turn_off
        entity_id:
          - switch.zwave_switch_1_switch
          - switch.zwave_switch_2_switch
          - switch.zwave_switch_3_switch
          - switch.zwave_switch_4_switch
          - switch.zwave_switch_5_switch
          - switch.zwave_switch_6_switch
          - switch.zwave_switch_7_switch
          - switch.smart_socket_1
          - switch.smart_socket_2
      - service: lock.lock
        entity_id: group.all_locks
      - service: media_player.turn_off
        entity_id:
          - media_player.living_room
          - media_player.firetv
      - service: media_player.pause
        entity_id:
          - media_player.spotify
      - condition: numeric_state
        entity_id: sensor.dark_sky_temperature
        above: 60
      - service: fan.turn_on
        entity_id: fan.zwave_fan_1_level
        data:
          speed: 'low'
  - alias: Don't sleep yet
    trigger:
      platform: state
      entity_id: switch.sleeping
      to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.any_door_open
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.sleeping
      - service: script.turn_on
        entity_id: script.play_tts
        data_template:
          variables:
            message: >
              {% set doors = ["door_one", "door_two", "door_three", "door_four", "door_five"] %}
              {% for door in doors %}
                {% if states.binary_sensor[door].state == 'on' -%}
                  The {{states.binary_sensor[door].attributes.friendly_name.lower()}} is open and must be closed.
                {%- endif -%}
              {% endfor %}
  - alias: Turn off sleep mode automatically
    trigger:
      platform: time
      at: '10:00:00'
    condition:
    - condition: state
      entity_id: switch.sleeping
      state: 'on'
    action:
      service: homeassistant.turn_off
      data:
        entity_id: switch.sleeping
