homeassistant:
  customize:
    switch.everspring_se812_siren_switch_29_0:
      hidden: true
    script.scare_pests:
      icon: mdi:play
      friendly_name: Short Siren
    binary_sensor.siren:
      icon: mdi:bullhorn

group:
  Pests:
    - camera.backyard
    - script.scare_pests
    - binary_sensor.siren

binary_sensor:
  - platform: template
    sensors:
      siren:
        value_template: "{{ states.switch.everspring_se812_siren_switch_29_0.state == 'on' }}"

script:
  scare_pests:
    sequence:
      - service: switch.turn_on
        entity_id: switch.everspring_se812_siren_switch_29_0
      - delay:
          seconds: 2
      - service: switch.turn_off
        entity_id: switch.everspring_se812_siren_switch_29_0

automation:
  - alias: Ensure alarm doesn't stay on
    trigger:
      platform: state
      entity_id: switch.everspring_se812_siren_switch_29_0
      to: 'on'
      for:
        seconds: 4
    action:
      - service: switch.turn_off
        entity_id: switch.everspring_se812_siren_switch_29_0
