homeassistant:
  customize:
    switch.zwave_siren_switch:
      hidden: true
    script.scare_pests:
      icon: mdi:play
      friendly_name: Short Siren
    binary_sensor.siren:
      icon: mdi:bullhorn

group:
  Pests:
    - camera.backyard
    - script.scare_pests
    - binary_sensor.siren

binary_sensor:
  - platform: template
    sensors:
      siren:
        value_template: "{{ states.zwave_siren_switch.state == 'on' }}"

script:
  scare_pests:
    sequence:
      - service: switch.turn_on
        entity_id: switch.zwave_siren_switch
      - delay:
          seconds: 2
      - service: switch.turn_off
        entity_id: switch.zwave_siren_switch

automation:
  - alias: Ensure alarm doesn't stay on
    trigger:
      platform: state
      entity_id: switch.zwave_siren_switch
      to: 'on'
      for:
        seconds: 4
    action:
      - service: switch.turn_off
        entity_id: switch.zwave_siren_switch
