automation:
  - alias: Notify regional alerts
    trigger:
      platform: event
      event_type: mailgun_message_received
      event_data:
        from: !secret regional_notification_sender
    condition:
      - condition: state
        entity_id: switch.sleeping
        state: 'off'
    action:
      - service: persistent_notification.create
        data_template:
          title: '{{trigger.event.data.subject}}'
          message: '{{trigger.event.data["stripped-text"].split("\n")[6].split(" View")[0]}}'
      - service: script.turn_on
        entity_id: script.play_tts
        data_template:
          variables:
            message: '{{trigger.event.data["stripped-text"].split("\n")[6].split(" View")[0]}}'
