homeassistant:
  customize:
    sensor.glances_sensor_cpu_load:
      friendly_name: CPU Load
      icon: mdi:memory
    sensor.glances_sensor_disk_use:
      friendly_name: Disk
      icon: mdi:harddisk
    sensor.glances_sensor_ram_use:
      friendly_name: Memory
      icon: mdi:server
    sensor.process_mosquitto:
      friendly_name: mosquitto
    sensor.process_postgres:
      friendly_name: postgres
    sensor.process_snapserver:
      friendly_name: snapserver
    sensor.process_glances:
      friendly_name: glances
  customize_glob:
    'sensor.process_*':
      icon: mdi:check

group:
  Server:
    - sensor.glances_sensor_cpu_load
    - sensor.glances_sensor_disk_use
    - sensor.glances_sensor_ram_use
    - sensor.ups_battery
  Services:
    - sensor.process_mosquitto
    - sensor.process_postgres
    - sensor.process_glances
    - sensor.process_snapserver

apcupsd:
  host: localhost
  port: 3551

panel_iframe:
  system:
    title: Server
    icon: mdi:server
    url: !secret glances_url

sensor:
  - platform: glances
    name: Glances sensor
    host: localhost
    port: 61208
    resources:
      - disk_use_percent
      - memory_use_percent
      - processor_load
  - platform: apcupsd
    resources:
      - bcharge
#  - platform: systemmonitor
#    resources:
#      - type: process
#        arg: mosquitto
#      - type: process
#        arg: snapserver
#      - type: process
#        arg: glances
#      - type: process
#        arg: postgres
