homeassistant:
  customize:
    - entity_id: sensor.glances_sensor_cpu_load
      friendly_name: CPU Load
      icon: mdi:memory
    - entity_id: sensor.glances_sensor_disk_use
      friendly_name: Disk
      icon: mdi:harddisk
    - entity_id: sensor.glances_sensor_ram_use
      friendly_name: Memory
      icon: mdi:server

group:
  Server:
    - sensor.glances_sensor_cpu_load
    - sensor.glances_sensor_disk_use
    - sensor.glances_sensor_ram_use
    - sensor.ups_battery

apcupsd:
  host: localhost
  port: 3551

panel_iframe:
  system:
    title: Server
    icon: mdi:server
    url: !secret glances_url

sensor:
  - platform: glances
    name: Glances sensor
    host: localhost
    port: 61208
    resources:
      - disk_use_percent
      - memory_use_percent
      - processor_load
  - platform: apcupsd
    resources:
      - bcharge
