#########################################################################
# Twitch
#
#  Monitor streamers on twitch.tv.
#########################################################################

homeassistant:
  customize:
    switch.twitch:
      friendly_name: Twitch Alerts
      icon: mdi:twitch

sensor:
  - platform: twitch
    entity_namespace: twitch
    client_id: !secret twitch_client_id
    channels:
      - fopt_membrillo
      - tyrant_theviper
      - t90official

switch:
  - platform: mqtt
    name: 'Twitch'
    state_topic: 'twitch/enabled'
    command_topic: 'twitch/enabled'
    qos: 1
    payload_on: 'yes'
    payload_off: 'no'
    retain: true

group:
  Twitch:
    - sensor.twitch_fopt_membrillo
    - sensor.twitch_t90official
    - sensor.twitch_tyrant_theviper
    - weblink.twitch
    - switch.twitch

automation:
  # Streamer online notifications.
  - alias: Streaming
    trigger:
      platform: state
      entity_id:
        - sensor.twitch_fopt_membrillo
        - sensor.twitch_t90official
        - sensor.twitch_tyrant_theviper
      to: 'streaming'
      for:
        seconds: 30
    condition:
      - condition: state
        entity_id: device_tracker.his_phone
        state: 'home'
      - condition: state
        entity_id: switch.sleeping
        state: 'no'
      - condition: state
        entity_id: switch.twitch
        state: 'yes'
    action:
      service: notify.him
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} is streaming
