#########################################################################
# Vehicles
#
#  Everything to do with vehicles.
#########################################################################

homeassistant:
  customize:
   sensor.2014_jeep_patriot:
     hidden: true
   sensor.2015_ram_1500:
     icon: 'mdi:car-pickup'
   device_tracker.2015_ram_1500:
     icon: 'mdi:car-pickup'
   sensor.gas_price:
     icon: 'mdi:gas-station'
   sensor.gas_tank:
     icon: 'mdi:fuel'
   script.lock_truck:
     friendly_name: 'Lock Truck'
     icon: 'mdi:lock'
   script.unlock_truck:
     friendly_name: 'Unlock Truck'
     icon: 'mdi:lock-open-outline'
   script.truck_on:
     friendly_name: 'Start Truck'
     icon: 'mdi:engine'
   script.truck_off:
     friendly_name: 'Stop Truck'
     icon: 'mdi:engine-outline'
   script.truck_horn:
     friendly_name: 'Truck Panic'
     icon: 'mdi:bullhorn'

sensor:
  # Connect to Mopar uConnect online portal.
  - platform: mopar
    username: !secret mopar_username
    password: !secret mopar_password
    pin: !secret mopar_pin
  # Get local gas price.
  - platform: rest
    scan_interval: 3600
    resource: !secret gas_buddy_resource
    method: GET
    name: Gas Price
    value_template: '{{value_json.trends[0].Today}}'
    unit_of_measurement: '$/gal'
  # Extract fuel level from device tracker.
  - platform: template
    sensors:
      gas_tank:
        entity_id: "device_tracker.2015_ram_1500"
        value_template: '{{states.device_tracker["2015_ram_1500"].attributes.fuel_level}}'
        friendly_name: 'Gas Tank'
        unit_of_measurement: '%'

# Track vehicle with Automatic (3G OBD-II adapter).
device_tracker:
  - platform: automatic
    client_id: !secret automatic_client_id
    secret: !secret automatic_secret
    current_location: false

script:
  # Send a remote command to lock vehicle.
  lock_truck:
    sequence:
      - service: mopar.remote_command
        data:
          vehicle_index: 0
          command: lock
  # Send a remote command to unlock vehicle.
  unlock_truck:
    sequence:
      - service: mopar.remote_command
        data:
          vehicle_index: 0
          command: unlock
  # Send a remote command to start vehicle.
  truck_on:
    sequence:
      - service: mopar.remote_comand
        data:
          vehicle_index: 0
          command: engineon
  # Send a remote command to turn off vehicle.
  truck_off:
    sequence:
      - service: mopar.remote_command
        data:
          vehicle_index: 0
          command: engineoff
  # Send a remote command to trigger panic mode (horn & lights).
  truck_horn:
    sequence:
      - service: mopar.remote_command
        data:
          vehicle_index: 0
          command: horn

# Group vehicle-related entities.
group:
  Vehicles:
    - device_tracker.2015_ram_1500
    - sensor.2015_ram_1500
    - sensor.gas_tank
    - sensor.gas_price
    - script.lock_truck
    - script.unlock_truck
    - script.truck_on
    - script.truck_off
    - script.truck_horn
