homeassistant:
  customize:
   sensor.2014_jeep_patriot:
     hidden: true
   sensor.2015_ram_1500:
     icon: 'mdi:car-pickup'
   device_tracker.2015_ram_1500:
     icon: 'mdi:car-pickup'
   sensor.gas_price:
     icon: 'mdi:gas-station'
   sensor.gas_tank:
     icon: 'mdi:fuel'
   script.lock_truck:
     friendly_name: 'Lock Truck'
     icon: 'mdi:lock'
   script.unlock_truck:
     friendly_name: 'Unlock Truck'
     icon: 'mdi:lock-open-outline'
   script.truck_on:
     friendly_name: 'Start Truck'
     icon: 'mdi:engine'
   script.truck_off:
     friendly_name: 'Stop Truck'
     icon: 'mdi:engine-outline'
   script.truck_horn:
     friendly_name: 'Truck Panic'
     icon: 'mdi:bullhorn'

sensor:
  - platform: mopar
    username: !secret mopar_username
    password: !secret mopar_password
    pin: !secret mopar_pin
  - platform: rest
    scan_interval: 3600
    resource: !secret gas_buddy_resource
    method: POST
    name: Gas Price
    value_template: '{{value_json.trend.Today}}'
    unit_of_measurement: '$/gal'
  - platform: template
    sensors:
      gas_tank:
        value_template: '{{states.device_tracker["2015_ram_1500"].attributes.fuel_level}}'
        friendly_name: 'Gas Tank'
        unit_of_measurement: '%'

device_tracker:
  - platform: automatic
    client_id: !secret automatic_client_id
    secret: !secret automatic_secret
    current_location: false

script:
  lock_truck:
    sequence:
      - service: mopar.remote_command
        data:
          vehicle_index: 0
          command: lock
  unlock_truck:
    sequence:
      - service: mopar.remote_command
        data:
          vehicle_index: 0
          command: unlock
  truck_on:
    sequence:
      - service: mopar.remote_comand
        data:
          vehicle_index: 0
          command: engineon
  truck_off:
    sequence:
      - service: mopar.remote_command
        data:
          vehicle_index: 0
          command: engineoff
  truck_horn:
    sequence:
      - service: mopar.remote_command
        data:
          vehicle_index: 0
          command: horn

group:
  Vehicles:
    - device_tracker.2015_ram_1500
    - sensor.2015_ram_1500
    - sensor.gas_tank
    - sensor.gas_price
    - script.lock_truck
    - script.unlock_truck
    - script.truck_on
    - script.truck_off
    - script.truck_horn
