homeassistant:
  customize:
    - entity_id:
        - sensor.vision*
        - sensor.schlage*
        - sensor.linear*
        - sensor.first_alert*
        - binary_sensor.*
      hidden: True


panel_iframe:
  ozwcp:
    title: OZWCP
    icon: mdi:signal-variant
    url: !secret ozwcp_url

zwave:
  usb_path: /dev/ttyACM0
  config_path: !secret zwave_config_path
