homeassistant:
  customize_glob:
    'sensor.zwave_*':
      hidden: True
    'binary_sensor.zwave_door_*':
      hidden: True
    #'zwave.*':
    #  hidden: True

cover:
  platform: zwave

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    fan.zwave_fan_1_level:
      polling_intensity: 3
