homeassistant:
  customize_glob:
    'sensor.vision*':
      hidden: true
    'sensor.schlage*':
      hidden: true
    'sensor.linear*':
      hidden: true
    'sensor.first_alert*':
      hidden: true
    'binary_sensor.vision*':
      hidden: True
    'zwave.*':
      hidden: True


panel_iframe:
  ozwcp:
    title: OZWCP
    icon: mdi:signal-variant
    url: !secret ozwcp_url

cover:
  platform: zwave

zwave:
  usb_path: /dev/ttyACM0
  config_path: !secret zwave_config_path
