alias: Carbon monoxide detected
trigger:
  platform: state
  entity_id: group.detectors
  state: 'Carbon Monoxide'
action:
  - service: notify.all
    data_template:
      message: 'Carbon monoxide detected!'
